url: https://github.com/projectcalico/calico/releases/download/v3.20.1/tigera-operator-v3.20.1.tgz
packageVersion: 02
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
